// Run once: node scripts/encode-fonts.mjs
// Encodes the Noto Sans TTF (already in Next.js node_modules) into a TS module
// so jsPDF can use it without any runtime HTTP fetch.

import { readFile, writeFile } from 'fs/promises';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const regularPath = 'C:/Windows/Fonts/arial.ttf';
const boldPath    = 'C:/Windows/Fonts/arialbd.ttf';

const [regularBuf, boldBuf] = await Promise.all([
  readFile(regularPath),
  readFile(boldPath),
]);

const regularB64 = regularBuf.toString('base64');
const boldB64    = boldBuf.toString('base64');

const ts = `// Auto-generated by scripts/encode-fonts.mjs — do not edit manually.
// Arial Regular + Bold from Windows Fonts — full Latin Extended-A support (ć č š ž đ).
export const ARIAL_REGULAR = '${regularB64}';
export const ARIAL_BOLD    = '${boldB64}';
`;

const outPath = join(__dirname, '../src/lib/pdf/pdfFonts.ts');
await writeFile(outPath, ts);
console.log('Done — pdfFonts.ts written (regular: ' + Math.round(regularB64.length / 1024) + ' KB, bold: ' + Math.round(boldB64.length / 1024) + ' KB)');
